### ISSUE TITLE
List archived devices, archive and unarchive a device  label:enhancement 

### ISSUE THREAD

**Issue by michaelrosejr** [Pack3tL0ss/central-api-cli#195]
Please add the ability to 

- List devices that have been archived
- Archive a device
- Unarchive a device

**Comment by Pack3tL0ss** [comment]
All 3 are in cencli, however un-archive is currently hidden.  I was considering making both archive and unarchive hidden as they don't necessarily have as much meaning with GLCP managing the devices.  

`cencli show archived` will show devices that are archived
`cencli archive <device> [device [device] ...]` will archive 1 or many devices (can specify multiple)
`cencli unarchive ...` same format as archive.  This command is currently hidden, but help text etc works you just have to type out unarchive 

`cencli delete device <device> [device [device] ...]`  and `cencli batch delete devices <file>`  have been adjusted, they will archive, then unarchive the devices which removes the association with the Central cluster in GL, then they will wait for any devices that were connected to show offline in central and remove it from the monitoring views.  Effectively it removes the association with Central, the subscription assignment, and all group/site/label associations, as well as removing it from the device list in the Central UI.  I believe it still remains in the GL inventory until it's been added/assigned elsewhere, but this sequence allows you to move it to a different cluster.

With the delete option, I didn't see a need to expose archive/unarchive directly.  I don't see a scenario where archive does anything useful for GL other than the flow now built into the delete command.

**Comment by Pack3tL0ss** [comment]
Just cleaning up/closing.  unarchive works now, but is hidden.  archive then unarchive removes both the subscription and the association with the central app.  So after it's been unarchived it will show in GL in the device list, but it won't be associated with Central so it won't appear in the central inventory (`/platform/device_inventory/v1/devices` or `cencli show inventory`).

I'll expose `unarchive` when I push the next update with a warning on archive or unarchive so the implications are clear.  You have to use `cencli add device serial <serial> mac <mac> --license <license>` to re-associate and subscribe the device after it's been unarchived.
